#ifndef ANIUM_VGUIPANEL_HPP
#define ANIUM_VGUIPANEL_HPP

enum VGuiPanel {
    PANEL_ROOT = 0,
    PANEL_GAMEUIDLL,
    PANEL_CLIENTDLL,
    PANEL_TOOLS,
    PANEL_INGAMESCREENS,
    PANEL_GAMEDLL,
    PANEL_CLIENTDLL_TOOLS
};

#endif  // ANIUM_VGUIPANEL_HPP
