version: 2
jobs:
  build:
    working_directory: ~/anium
    docker:
      - image: ubuntu:rolling
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update -qq
            apt-get install -y g++ clang-5.0 cmake git wget ssh patchelf
      - checkout
      - run:
          name: Init submodules
          command: |
            if [ ! -d "~/.ssh/" ]; then mkdir ~/.ssh; fi
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git submodule init
            git submodule update --remote --merge --recursive
      - run:
          name: Generate CMake files
          command: |
            cmake .
      - run:
          name: Build
          command: |
            make -j2
      - store_artifacts:
          path: ~/anium/bin/libAnium.so
          destination: libAnium.so
