version: 2
jobs:
  build:
    working_directory: ~/anium
    docker:
      - image: ubuntu:rolling
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update -qq
            apt-get install -y g++ clang cmake git wget ssh binutils-dev
      - checkout
      - run:
          name: Build using GCC
          command: |
            CC=gcc CXX=g++ cmake .
            make -j2
      - store_artifacts:
          path: ~/anium/bin/libAnium.so
          destination: gcc/libAnium.so
      - run:
          name: Build using Clang
          command: |
            rm -rf CMakeCache.txt
            rm -rf bin/
            CC=clang CXX=clang++ cmake .
            make -j2
      - store_artifacts:
          path: ~/anium/bin/libAnium.so
          destination: clang/libAnium.so

notify:
  webhooks:
    - url: https://rainly.herokuapp.com/circle/422205943414128652/jJvVvb07Hdf_53dBoORk_gJQGa4646niCmXAG5uag4nMqe-pXOAWi6wCsJeSs-YAqakt
